In [1]:
import pandas as pd

In [2]:
#задача1

In [4]:
stats = pd.read_csv('ratings.csv')
stats.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [7]:
def klassif(row):
    if row['rating'] >= 4.5: return 'высокий рейтинг'
    if row['rating'] <= 2.0: return 'низкий рейтинг'
    return 'средний рейтинг'

In [9]:
stats['klass_']=stats.apply(klassif,axis=1)

In [13]:
stats.head()

   userId  movieId  rating  timestamp           klass_
0       1        1     4.0  964982703  средний рейтинг
1       1        3     4.0  964981247  средний рейтинг
2       1        6     4.0  964982224  средний рейтинг
3       1       47     5.0  964983815  высокий рейтинг
4       1       50     5.0  964982931  высокий рейтинг

In [14]:
#задача2
#не смог я пристроить Библиотеку pymystem, поэтому просто обрезал окончания в словаре регионов

In [126]:
geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

In [162]:
stats = pd.read_csv('keywords.csv')
stats.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [163]:
def geo_reg(row):
    
    for i in geo_data:
        for g in geo_data[i]:
            if g[0:(len(g)-1)] in row['keyword']:
                #print(g[0:(len(g)-1)],row['keyword'])
                #print(i)
                return i
    return 'undefined'

In [164]:
stats['region']=stats.apply(geo_reg, axis=1)
stats.head(3000)

,keyword,shows,region
0,вк,64292779,undefined
1,одноклассники,63810309,undefined
2,порно,41747114,undefined
3,ютуб,39995567,undefined
4,вконтакте,21014195,undefined
5,одноклассники моя страница,19976138,undefined
6,майл,15144673,undefined
7,авито,14786593,undefined
8,переводчик,14453469,undefined
9,яндекс,13344734,undefined
10,сбербанк онлайн,10725673,undefined
11,mail,7687204,undefined
12,игры,6075762,undefined
13,youtube,5729958,undefined
14,вконтакте моя страница,5971451,undefined
15,секс,5431732,undefined
16,гугл,5175471,undefined
17,dr,4880955,undefined
18,алиэкспресс,4879645,undefined
19,рамблер,4540421,undefined
20,фильмы 2016,4486635,undefined
21,погода,4344510,undefined
22,vk,4330448,undefined
23,ютуб видеохостинг,4215267,undefined
24,дойки,4133424,undefined
25,одноклассники социальная сеть,4018230,undefined
26,мультики,3866664,undefined
27,контакт,3815111,undefined
28,фейсбук,3669993,undefined
29,порно видео,3858938,undefined
...,...,...,...
2970,герой нашего времени,74873,undefined
2971,гисметео спб,75133,undefined
2972,vk com вконтакте,74990,undefined
2973,баста,74832,undefined
2974,авто ру санкт петербург,74918,Северо-Запад
2975,кэтрин уинник,74938,undefined
2976,каспийский груз,74839,undefined
2977,проверка штрафов гибдд,88960,undefined
2978,ужасы онлайн самые страшные и лучшие фильмы уж...,74906,undefined
2979,папарацци,74659,undefined
2980,погода в волгограде на 14 дней,73576,undefined
2981,слуга народа 2,77675,undefined
2982,тануки,74561,undefined
2983,первый человек в открытом космосе,74825,undefined
2984,пфр,74543,undefined
2985,mediaget,74535,undefined
2986,дом 2 онлайн смотреть бесплатно,122150,undefined
2987,мужское и женское первый канал все выпуски,73345,undefined
2988,мешок,74520,undefined
2989,корабль,74507,undefined
2990,бобсоккер,74486,undefined
2991,скайп скачать бесплатно,143902,undefined
2992,рыбалка,74456,undefined
2993,метро спб,77135,undefined
2994,леон,74416,undefined
2995,спокойной ночи малыши,74406,undefined
2996,кун уз,74767,undefined
2997,викинг фильм 2017 смотреть онлайн полностью бе...,74494,undefined
2998,х,74379,undefined
2999,rp5,74371,undefined